### ISSUE TITLE
Allow "REF" to be used as Column Name

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#28]
We have several tables with columns named "ref" which is working, but the sonar-plsql parser throws a parsing error.

Testcase aded to CreateViewTest.java:
```
    @Test
    public void matchesDecodeWithRefColumn() {
    	assertThat(p).matches("create or replace view foo as select decode(bp.ref,null,sp.name1,bp.name1) p_name1 from bp, sp;");
    }
```
produces
```
org.sonar.sslr.tests.ParsingResultComparisonFailure: Rule 'CREATE_VIEW' should match:
create or replace view foo as select decode(bp.ref,null,sp.name1,bp.name1) p_name1 from bp, sp;
Parse error at line 1 column 47:

  -->  create or replace view foo as select decode(bp.ref,null,sp.name1,bp.name1) p_name1 from bp, sp;EOF

	at org.sonar.sslr.tests.ParserAssert.matches(ParserAssert.java:72)
	at org.sonar.plugins.plsqlopen.api.units.CreateViewTest.matchesDecodeWithRefColumn(CreateViewTest.java:132)
```

I tried marking `org.sonar.plugins.plsqlopen.api.PlSqlKeyword.REF` as non reserved keyword which resolves above error but let's fail 

`org.sonar.plugins.plsqlopen.api.declarations.VariableDeclarationTest.matchesRefObjectDeclaration()` 

I tried to look into that but was not able to resolve that failing test, Any suggestions or feddback would be very welcome.

Thanks, 
bye Peter

**Comment by felipebz** [comment]
Hi Peter.

The problem is the definition of the DATATYPE rule: https://github.com/felipebz/sonar-plsql/blob/5518c5551aaab834686620baae45209851e1fad3/plsql-frontend/src/main/java/org/sonar/plugins/plsqlopen/api/PlSqlGrammar.java#L313-L325

SSLR tries to match the rules in a firstOf in the same order as specified in the code. I don't remember the implementation details from SSLR but, since REF ia a valid identifier, the DATATYPE rule is trying to parse "ref custom" (from the failing test) first as a CUSTOM_DATATYPE and it doesn't even try to check if it's a REF_DATATYPE.

Quick fix: in the definition of DATATYPE rule, REF_DATATYPE should be before the CUSTOM_DATATYPE. :-)
