### ISSUE TITLE
procedure definition in .pkb and .pks are counted as code duplication

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#36]
Hi,

when creating a procedure definition in a PL/SQL package the signature needs to be defined in the package specification(.pks) and in the package body(.pkb).

It seems like this is counted as code duplication which does not seem correct to me since it can't be avoided. 
Is there anything we can do about that?

Thanks!

**Comment by felipebz** [comment]
Hi.

Currently we just get all the tokens from the lexer and register them with the Copy/Paste Detector API:

https://github.com/felipebz/sonar-plsql/blob/96f19ed68db6b76b3f502bff3cac3bdd02d09a7c/sonar-plsql-open-plugin/src/main/java/org/sonar/plsqlopen/PlSqlSquidSensor.java#L181-L189

I've looked the source of other plugins and found that sonar-cxx has a very interesting approach using a [visitor](https://github.com/SonarOpenCommunity/sonar-cxx/blob/7ae8421178cc8e28a16085765ac7aeb7ac63d0e6/cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxCpdVisitor.java) to restrict the duplication detection to function declarations.

I'll try to implement this and restrict the CPD to package bodies, procedures and functions. This should even bring a small performance improvement in the analysis because the lexer won't need to be called twice (one time for the coding rules and another for the duplication detection).

**Comment by phermsdorf** [comment]
Cool! Thanks, great job!
