### ISSUE TITLE
Support type as column name in ANCHORED_DATATYPE

### ISSUE THREAD

**Issue by phermsdorf** [felipebz/sonar-plsql#37]
Hi,

we have tables with column name 'type' which leads to parsing errors when used in type definitions like:

```
create procedure test as
v_blah tab.name%type;
begin
  null;
end;

```
I think the problem is in the definition of the MEMBER_EXPRESSION which explicitly disallows the usage of the 'type' keyword. But simply removing it leads to a lot of problems in other places

```
b.rule(MEMBER_EXPRESSION).is(
                MULTIPLE_VALUE_EXPRESSION,
                b.zeroOrMore(
                        b.firstOf(DOT, MOD, REMOTE),
                        b.nextNot(ROWTYPE),
  --->                b.nextNot(TYPE),
                        b.firstOf(
                                IDENTIFIER_NAME,
                                COUNT,
                                ROWCOUNT,
                                BULK_ROWCOUNT,
                                FIRST,
                                LAST,
                                LIMIT,
                                NEXT,
                                PRIOR,
                                EXISTS,
                                FOUND,
                                NOTFOUND,
                                ISOPEN,
                                DELETE)
                        )).skipIfOneChild();

```
![image](https://user-images.githubusercontent.com/11061378/32963281-ca4b41f6-cbcf-11e7-8e26-8cd0ab14625a.png)

So in need some advice to fix this issue ;)

Thanks.

Bye Peter

**Comment by felipebz** [comment]
The MEMBER_EXPRESSION matches things like "pkg.proc", "pkg.proc@link" and "mycursor%rowcount". But we need a way to distinguish between this from an anchored datatype (tab.col%type).

The b.nextNot(TYPE) in MEMBER_EXPRESSION is required to "tab.col%type" be parsed as a DATATYPE (MEMBER_EXPRESSION%TYPE) instead of a MEMBER_EXPRESSION (IDENTIFIER.IDENTIFIER%TYPE).

But as you find out the definition is too broad and it disallows "tab.type". In the MEMBER_EXPRESSION definition, the b.nextNot(TYPE) should be applied only after %, not . or @. ;-)

**Comment by phermsdorf** [comment]
Thanks!
