### ISSUE TITLE
BULK is not a reserved keyword 

### ISSUE THREAD

**Issue by vinupriyesh** [felipebz/sonar-plsql#48]
Hi, 
 According to oracle PLSQL ([link](https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/reservewords.htm)), bulk is not a reserved keyword. i.e. it can be used as an identifier but it is not recommended.   

  As of today in this project 'BULK' is a reserved keyword, and it fails to parse any PLSQL statements with BULK as an identifier.  

Example:  
```
DECLARE
bulk NUMBER;
BEGIN
NULL;
END;
```

Changing 'bulk' as non-reserved keyword doesn't help as it breaks the build for regular select statement.  Like in unit test for
```sql
select 1 bulk collect into var from dual
```

here, it is considering 'bulk' as an alias identifier name and fails to parse this query.   Having said that even the below statements are possible and perfectly valid according to oracle.

```sql
select 1 bulk bulk collect into var from dual
select 1 bulk into var from dual
```

I agree having 'bulk' in source code as an identifier is not 'correct' and it is a very bad practice.  But even someone might've named a column 'BULK' and the usage of that column in any unit would fail to parse.  Like,   
`l_table_abc.bulk := 'some bulk data';`

Any ideas on how to go with it?

**Comment by felipebz** [comment]
Hi @vinupriyesh.

You're right about why the parser fails.

Considering that "select 1 anything collect into..." is not valid SQL, we can also say that an alias cannot be followed by the "collect" keyword. Using this information, the parser can distinguish "select 1 bulk collect" (SELECT VALUE INTO_CLAUSE, because 'bulk' can't be an alias here) from "select 1 bulk bulk collect" (SELECT VALUE ALIAS INTO_CLAUSE, the first 'bulk' is an alias for sure, the next token is BULK).

The easiest fix is to change the SELECT_COLUMN rule to not match an alias if it's followed by "collect".

I've fixed this in master. ;-)

**Comment by vinupriyesh** [comment]
Cool.  it works fine now. thank you :+1:
