### ISSUE TITLE
Parse Issue

### ISSUE THREAD

**Issue by ivan-vinn** [felipebz/sonar-plsql#5]
Hi Felipe,

I'm trying to use your plugin on a set of sql files.

When i'm launching sonar-scanner i've "ERROR: Unable to parse file" on every file.

I'm using Sonar 5.6 and last build of your plugin (sonar-plsql-open-plugin-1.0-SNAPSHOT.jar)

i've tried to launch the scanner using -X but there are no debug messages.

Some logs:
(I've masked some file and tables names)

> ....
> INFO: Sensor PHPUnit Sensor (done) | time=2ms
> INFO: Sensor PlSqlSquidSensor
> INFO: 78 source files to be analyzed
> ERROR: Unable to parse file: <masked>/SQL/etl_00_<masked>.sql
> ERROR: Parse error at line 1 column 0:
> 
>   -->  TRUNCATE <masked>.CON<masked>I_T;
>     2: TRUNCATE <masked>.JOI<masked>PRC;
>     3: TRUNCATE <masked>.PCA<masked>SX;
>     4: TRUNCATE <masked>.PCB<masked>RI;
>     5: TRUNCATE <masked>.POL<masked>;
>     6: TRUNCATE <masked>.POL<masked>RIZZO;
> 
> ERROR: Unable to parse file: <masked>/SQL/etl_01_<masked>.sql
> ERROR: Parse error at line 1 column 0:
> 
>   -->  TRUNCATE <masked>.CON<masked>;
>     2: TRUNCATE <masked>.JOI<masked>C;
>     3: TRUNCATE <masked>.PCA<masked>SX;
>     4: TRUNCATE <masked>.PCB<masked>I;
>     5: TRUNCATE <masked>.POL<masked>;
>     6: TRUNCATE <masked>.POL<masked>IZZO;
> 
> ERROR: Unable to parse file: <masked>/SQL/etl_02_<masked>.sql
> ERROR: Parse error at line 1 column 0:
> 
>   -->  UPDATE `<masked>`.`<masked>` AS SOG
>     2: JOIN `<masked>`.`PSSI<masked>S_CB` AS <masked>
>     3: SET
> 
> 	
> 	.....

TY for your help.

**Comment by felipebz** [comment]
Hi.

The support of SQL scripts is very limited at this moment, because I'm focused on the PL/SQL support.

Anyway, I want to parse the Oracle SQL syntax and those TRUNCATE statements aren't valid in Oracle (they cause an "ORA-03290: Invalid truncate command - missing CLUSTER or TABLE keyword").

The UPDATE with JOIN isn't valid in Oracle too (ORA-00971: missing SET keyword).

Sorry, but I don't have any plans to support other databases at this moment.

**Comment by ivan-vinn** [comment]
TY for your help.
