### ISSUE TITLE
Parsing file with maven placeholders

### ISSUE THREAD

**Issue by dwarcake** [felipebz/sonar-plsql#52]
We are currently installing our sources with Liquibase via Maven.
In some of our files ( grants, synonyms mostly) we use palceholders so we can dynamicly change the statement.

Now in Jenkins when analyzing the sources, we get errors like this:
```
[Build develop] ERROR: Parse error at line 1 column 27:
[Build develop] 
[Build develop]   -->  grant all on <table> to ${project_user};
```

Is there a way to work around this ?

Regards,

Kim

**Comment by felipebz** [comment]
Hi @dwarcake.

Short answer: with the current release there's not way to work around this.

But... I've just added an error recovery mechanism to the parser. Starting from the next version, the analysis will try to ignore unrecognized commands instead of breaking the analysis of the whole file.

Please see this example:

![image](https://user-images.githubusercontent.com/13829/35950511-0ef9801e-0c5e-11e8-8f0c-117e394e61a9.png)

Note that even with the invalid command, the parser was able to continue the analysis and it registered the violations.

**Comment by dwarcake** [comment]
Hi Felipe,

Thanks for the information.
Looking forward to the next release then :)
