### ISSUE TITLE
Variable substitution

### ISSUE THREAD

**Issue by jgarec** [felipebz/sonar-plsql#71]
Hi,

Note sure it's an issue but i need to know how to deal with variable substituion.
Our scripts contain some substitution like this :

```
CREATE OR REPLACE PACKAGE BODY &&OWN_USER..MY_PKG AS
[...]
```

Sonar-scanner fails with the following message :
```
ERROR: Parse error at line 1 column 36:
  -->  CREATE OR REPLACE PACKAGE           ..MY_PKG AS
```

If i use double quotes around the variable, it's ok in this case but i'm not sure it works in all case :
```
CREATE OR REPLACE PACKAGE BODY "&&OWN_USER.".MY_PKG AS
[...]
```

**Comment by felipebz** [comment]
Hi @jgarec.

It's a hard problem because these variable substitutions can appear anywhere... I'm not sure how this can be fixed. In the version 2.1 the plugin was "improved" to just ignore completely the parsing failures and not interrupt the analysis of the whole file. You can read more about this in https://github.com/felipebz/sonar-plsql/wiki/Error-recovery

The drawback of this approach is that the code inside the package won't be analyzed and won't register any issue in SonarQube.

I don't know what SonarSouce is doing on its plugin. Is it able to identify issues inside this package?
